server:
  port: 8080
  servlet:
    session:
      timeout: 3600


# Identity Provider
idp:
  entity_id: sample_idp
  base_url: http://localhost:8080
  # openssl req -x509 -sha256 -nodes -days 3650 -newkey rsa:2048 -keyout gik044107.key -out gik044107.crt
  private_key : MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDYm9mL4zAwLf2Uarf7N3Wrs3Nmn0Mg7hD0X+zlO5W6qXaP/jHhP2jxj8/0n4z3IWakk3kkXw6n4r9kdGZi2Ikuf3cb0Bh6CwmljCkZtsb0ilcd32JsfM++ekKAWL9t2jgBLoeBGczrQcxxosfAL2mizeq01YLs2PkuxHhTinv8oPA1x0I3gOGk3REtdspowfvbofvAjx2TQymrIl1+LPpdjyvMgKzt0U/za/BNh9WzzBvT92Qg1zMdo+sSS76BPhesYP+O2LK0I5bbhPPoboNs2Sqorek3yZNdKg7Uoh4p4t0sIPtFfx+h7xoMVrgOwPldpMLcdB2Vi+LC9J+VCRRzAgMBAAECggEADt/w+grBceWOnuUPOliuI3rgx2DTdszybB20Qm+rkhR2GGBP45R7q+8AzF8yinwINPANpyJB+uR22TqnF02gagmFz+qj66mbYXt1DReApSVk4x/GfgW6LG3v6ClwB+au5uHfm01+xX8Qv5L6naeD3RK/9egdpA8oWX5TdwUxC4GPcwQRz82/jxd3ULbF/ikHXMFMlAnnztgzrB3VrOYSzXSU4MyuRQvjk9rvdhOYAFxv1FTPGgYhVcFwRHwSfFjeXZWcQFI2ZfHnjom3VwGPqpGRGFScQuKgn/IhOPX0J5yQTeu9yyyz3EBy5txcmrAV0VAUhEF0g7lWcpBl1wSAfQKBgQDlfrvKabCxm3Cz8rSKDyy2W0dL8yLfk0IIgorJYrdBbEivsZl2V2W9NeNs4QjkCNT2kOCPhXoN4gZGxBkFmn5nnpKHy5zLrZYGhA+j8PlAZYbBRuW6FnYv0nk2RW9X+hquCBuzDJ0GLC9ikx8IJ7N21ysaa6km13MDp63vXFHQhwKBgQDxoB67h6Up7liEd9/C/AnZ3QkDSW2AmGRqxmJKmgmw5FdU3OXYF7vT1B1p99rj56JZ64n+Odqbo/OIfodsDr7ZzvPgoSnUaoHCtuREzhTkmJ18wZ4Orc2215Tg6nweH5Yh3Ah72RCSDbi2HoDXEDmX8oeMCX7lfzjNIyJ88lxztQKBgBIP5WvK4bM4zqf7BCaRhy1bBcN+gVIjXuEYlR/AezfU8+uQCMn9mu5HXXzmQTLhVxGI2YOyN6b8EQ5kxKtiO2ygWFwDtHV7VgFxR2HZx2RAGVkA4XfB6M9eu1eAI4FDF/J2hOeUqI8hzyDs/1Y++aryyFut+YQrFMxG2DOsimvlAoGBAMlD9RWEMcGxta3yJENIqfP9uAoy2bGqPsrqIOm/UZ81NMGNly7e5ifWogGo4X3Bbmy0VCedjUjj0nG545fQ2IyZZG+SD0POy/OjYJUnjCO2NEi9Bql3gMly3aJT77sv2GCv5akz8CeYommhEvURoMe+z8WIC1mjFW9aetnVD8mZAoGALYdJh5ifGwoW7pvXwCkqHTcQ4nXLUCijM5IA66fsqsir66JDT1br1XN/wMYPCyCuRFxIKu853ZtH1oxeLsqZH2tnNwzpApZU7oS2fqML+UBO3PO84nCeiO87TlcyhEUZzBR2sLstF3nyEWnz6Gtb2Al+uffUd6Ga1XV44wERUDI=
  passphrase: gik044107@gmail.com
  certificate: MIID3zCCAsegAwIBAgIUSDoc6dJ/9O/IZ1Y+xhZOePdjlzMwDQYJKoZIhvcNAQELBQAwfzELMAkGA1UEBhMCa3IxDjAMBgNVBAgMBXNlb3VsMQ4wDAYDVQQHDAVzZW91bDELMAkGA1UECgwCZ2kxCzAJBgNVBAsMAmdpMRIwEAYDVQQDDAlsb2NhbGhvc3QxIjAgBgkqhkiG9w0BCQEWE2dpazA0NDEwN0BnbWFpbC5jb20wHhcNMjMwNDE2MTEyNjAwWhcNMzMwNDEzMTEyNjAwWjB/MQswCQYDVQQGEwJrcjEOMAwGA1UECAwFc2VvdWwxDjAMBgNVBAcMBXNlb3VsMQswCQYDVQQKDAJnaTELMAkGA1UECwwCZ2kxEjAQBgNVBAMMCWxvY2FsaG9zdDEiMCAGCSqGSIb3DQEJARYTZ2lrMDQ0MTA3QGdtYWlsLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANib2YvjMDAt/ZRqt/s3dauzc2afQyDuEPRf7OU7lbqpdo/+MeE/aPGPz/SfjPchZqSTeSRfDqfiv2R0ZmLYiS5/dxvQGHoLCaWMKRm2xvSKVx3fYmx8z756QoBYv23aOAEuh4EZzOtBzHGix8AvaaLN6rTVguzY+S7EeFOKe/yg8DXHQjeA4aTdES12ymjB+9uh+8CPHZNDKasiXX4s+l2PK8yArO3RT/Nr8E2H1bPMG9P3ZCDXMx2j6xJLvoE+F6xg/47YsrQjltuE8+hug2zZKqit6TfJk10qDtSiHini3Swg+0V/H6HvGgxWuA7A+V2kwtx0HZWL4sL0n5UJFHMCAwEAAaNTMFEwHQYDVR0OBBYEFOz4WWSbRJGuKPjIvDxR2mXiAJDZMB8GA1UdIwQYMBaAFOz4WWSbRJGuKPjIvDxR2mXiAJDZMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAFyWo/xPqgxdahEif+/8IjcNqlsZh4NfhziLNWtWjbSHDlF5eb9f+qtaOkuWvpgRcqrVDBPqu7y65iZNNeqn/xjvRJSFCD6K6NZWKVkoszXe8WALeMf/+TQCuT52du1Ta56fkd52rrgjzLU7Y/rm4aWGnTeHgnGBsVYYH0clquvfPRI2oR+ZBx9QqI1AiTOcV49fgrZ6GlyxTxPLYiyA7xbVo9ixtYrLx8oSCifCofqVADg7OyQeonjLkMqdvmgFZZJ7CoRhJLS7VFRsk8ZKV4zoaI7pghESq4ZoqQfNc/1r3UZ2Xeh4A57GCHXify0ZPYl5+FqcLKx2OsxGcmwu2KY=
  clock_skew: 300
  expires: 300
  sso_url: /sso
  slo_url: /slo


logging:
  level:
    root: info
    saml.example.idp: debug
    # debug filter chain
    org-hsqldb: DEBUG
    #org.springframework.security.web.FilterChainProxy: debug
    #org.springframework.security: DEBUG
    #org.springframework.security.authentication: DEBUG

spring:
  jpa:
    defer-datasource-initialization: true
    
    
    